---
title: "Dashboard_Salary"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(DT)
library(shiny)


```

Salary {}
=====================================

Row
-------------------------------------

### Distibution of Average of Minimum Salaries by Job 

```{r}

devtools::install_github("thiyangt/DSjobtracker")
library(DSjobtracker)

data("DStidy_2021")

df <- DStidy_2021


P <-  ggplot(df, aes(Job_Category,Salary)) + geom_col(position = "dodge", fill = "blue")+
  coord_flip() + labs(y = "Average Yearly Salaries in USD", x = "Job Title") + scale_fill_brewer(palette = "Blues") +
  theme_classic()

ggplotly(P)

```

Row
------------------------------------
### Distibution of Average of Minimum Salaries by Countries

```{r}
Q <- ggplot(df, aes(Country,Salary)) + geom_col(position = "dodge", fill = "blue")+
  coord_flip() + theme_classic() + labs(y = "Average Yearly Salaries in USD", x = "Country")

ggplotly(Q)

```



