---
title: "Experience"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```


```{r}
## Packages
library(tidyverse)
library(plotly)
library(DSjobtracker)
```


```{r}
## Install the data set
data("DStidy_2021")

```

column{}
----------------------------------------------------------------------

### Distribution of Minimun Years of Experience

```{r}
plot_ly(DStidy_2021,
        x = ~`Minimum Experience in Years`,
        type = "histogram") %>%
  layout(xaxis = list(title = "Minimum Required Experience in Years"),
         yaxis = list(title = "No of Job Advertisements"), 
         showlegend = FALSE)
```

column{.tabset}
-----------------------------------------------------------------------

### Distribution of Experience by Job Category


```{r}
data_exp <- DStidy_2021 %>% filter(Job_Category != "Others")
plot_ly(data_exp,
        x = ~Job_Category,
        y = ~`Minimum Experience in Years`,
        type = "box",
        color = ~Job_Category,
        colors = c("#1b9e77", "#d95f02", "#7570b3", "#e7298a")) %>%
  layout(xaxis = list(title  = "Job Category", tickangle = 0),
         yaxis = list(title = "Minimum Required Experience in Years"), showlegend = FALSE)
```


### Distribution of Experience by Educational Qualifications

```{r}
data <- DStidy_2021
data_new <- pivot_longer(data, c(110:112), names_to = "Education", values_to = "Value")


data_new <- data_new %>% filter(Value == "Yes")
plot_ly(data_new,
        x = ~Education,
        y = ~`Minimum Experience in Years`,
        type = "box",
        color = ~Education,
        colors = c("#e41a1c", "#377eb8", "#4daf4a")) %>%
  layout(xaxis = list(title  = "Minimum Educational Qualifications", tickangle = 0),
         yaxis = list(title = "Minimum Required Experience in Years"), showlegend = FALSE)

```

