---
title: "Job Field"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(DSjobtracker)
theme_set(theme_minimal())
data("DStidy_2021")
df <- DStidy_2021
# df <- read_csv("DStidy.csv") %>% 
#   mutate(Job_Field = str_replace(Job_Field,"Information technology","IT"))
# TODO R & Python by Job Field
# TODO Job Field Minimum years of experience and location
```

Column
--------------------------------------------------------------
### Composition of Job Fields

```{r}
jf_counts <- df %>%
  count(Job_Field) %>% 
  mutate(Job_Field = fct_reorder(factor(Job_Field),n)) 

l <- levels(jf_counts$Job_Field)

jf_counts %>% 
  mutate(Job_Field = fct_relevel(Job_Field,c("Other",l[l != "Other"]))) %>% 
  ggplot(aes(x = Job_Field,y = n))+
  geom_bar(stat="identity")+
  coord_flip()
```

Column {.tabset .tabset-fade}
--------------------------------------------------------------
### R and Python Requirements of Job Fields

```{r}
df %>% 
  group_by(Job_Field) %>% 
  summarize(Total = sum(R) + sum(Python),
            R= sum(R)*100/Total,Python = sum(Python)*100/Total) %>%
  ungroup() %>% 
  mutate(Job_Field = fct_reorder(Job_Field,R)) %>% 
  pivot_longer(cols= c("R","Python"), names_to = "Language",values_to = "Counts") %>% 
  ggplot(aes(x = Job_Field,y=Counts,fill=Language))+
  geom_bar(stat="identity") + 
  coord_flip() + 
  theme(legend.position = "bottom")+
  scale_fill_manual(values = c("#306998","#919198")) + 
  labs(x = "Job Field",y = "Percentage Proportion within Job Field")
```

### Tableau and Microsoft Power BI Requirements of Job Fields

```{r}
df %>% 
  group_by(Job_Field) %>% 
  summarize(Total = sum(Tableau) + sum(`Microsoft Power BI`),
            Tableau= sum(Tableau)*100/Total,`Microsoft Power BI` = sum(`Microsoft Power BI`)*100/Total) %>%
  ungroup() %>% 
  mutate(Job_Field = fct_reorder(Job_Field,Tableau)) %>% 
  pivot_longer(cols= c("Tableau","Microsoft Power BI"), names_to = "Language",values_to = "Counts") %>% 
  ggplot(aes(x = Job_Field,y=Counts,fill=Language))+
  geom_bar(stat="identity") + 
  coord_flip() + 
  theme(legend.position = "bottom")+
  scale_fill_manual(values = c("#ffba01","#c7233b")) + 
  labs(x = "Job Field",y = "Percentage Proportion within Job Field")
```

### Minimum experience needed in Job Fields

```{r}
df %>% 
  # group_by(Job_Field) %>% 
  # summarize(Average_Min_Exp = mean(`Minimum Experience in Years`,na.rm=TRUE)) %>% 
  ggplot(aes(x = Job_Field, y = `Minimum Experience in Years`))+
  geom_boxplot()+
  coord_flip()
```

