---
title: DS Jobtracker 2021 - English Requirement
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
library(flexdashboard)
library(devtools)
library(cli)
library(tidyverse)
library(magrittr)
library(readxl)
library(janitor)
library(treemapify)
library(treemap)
library(d3Tree)
library(gridExtra)
library(ggpubr)
library(stringr)
library(randomcoloR)
library(DSjobtracker)
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
devtools::install_github("thiyangt/DSjobtracker") 
data("DStidy_2021")
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
#Adjustment within job field column
DStidy_2021$Job_Field[DStidy_2021$Job_Field == "E commerce (online sales)"] <- "E commerce"


#Converting the first letter to capitals within job title field
DStidy_2021 <- DStidy_2021 %>%
  mutate(Job_title = str_to_title(Job_title))
```




```{r, warning=FALSE, message=FALSE, echo=FALSE}
#Creating job category column
DStidy_2021 <- DStidy_2021 %>%
  mutate(Job_Category = case_when(
    grepl(x = DStidy_2021$Job_title, pattern = "analyst", ignore.case = TRUE) ~ "Data Analyst",
    grepl(x = DStidy_2021$Job_title, pattern = "analytics", ignore.case = TRUE) ~ "Data Analyst",
    grepl(x = DStidy_2021$Job_title, pattern = "scientist", ignore.case = TRUE) ~ "Data Scientist",
    grepl(x = DStidy_2021$Job_title, pattern = "science", ignore.case = TRUE) ~ "Data Scientist",
    grepl(x = DStidy_2021$Job_title, pattern = "engineer", ignore.case = TRUE) ~ "Data Engineer"))

```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
#Recoding NA's as other within job category column
DStidy_2021$Job_Category[is.na(DStidy_2021$Job_Category)] <- "Other"

#Recoding the location column
DStidy_2021$Location[DStidy_2021$Location == "110 Healthy Way, Folosm, CA"] <- "United States"
DStidy_2021$Location[DStidy_2021$Location == "USA"] <- "United States"
DStidy_2021$Location[DStidy_2021$Location == "Anaheim, CA"] <- "United States"
DStidy_2021$Location[DStidy_2021$Location == "Bengaluru, Karnataka, India"] <- "India"
DStidy_2021$Location[DStidy_2021$Location == "Noida,Uttar Pradesh, India"] <- "India"
DStidy_2021$Location[DStidy_2021$Location == "Bloomington, IN"] <- "United States"
DStidy_2021$Location[DStidy_2021$Location == "canada"] <- "Canada"
DStidy_2021$Location[DStidy_2021$Location == "canda"] <- "Canada"
DStidy_2021$Location[DStidy_2021$Location == "Edinburgh,London,Manchester"] <- "United Kingdom"
DStidy_2021$Location[DStidy_2021$Location == "Melbone"] <- "Australia"
DStidy_2021$Location[DStidy_2021$Location == "Pennsylvania"] <- "United States"
DStidy_2021$Location[DStidy_2021$Location == "santa monica,CA"] <- "United States"
DStidy_2021$Location[DStidy_2021$Location == "NewYork"] <- "United States"
DStidy_2021$Location[DStidy_2021$Location == "SL"] <- NA
DStidy_2021$Location[DStidy_2021$Location == "Sri Lnaka"] <- NA
DStidy_2021$Location[DStidy_2021$Location == "Remote Work"] <- NA
DStidy_2021$Location[DStidy_2021$Location == "NA"] <- NA
DStidy_2021$Location[DStidy_2021$Location == "UK"] <- "United Kingdom"

```



```{r, warning=FALSE, message=FALSE, echo=FALSE}
#Converting selected columns to factors
fc1 <- c(8, 18)
DStidy_2021[,fc1] <- lapply(DStidy_2021[,fc1], factor)
```




## Column {data-width=500}

### English Requirement by Country
```{r, echo=FALSE, warning=FALSE, message=FALSE}
#Renaming categories within the English Needed column
levels(DStidy_2021$`English Needed`) <- c("No", "Yes")

#2021 English requirement by country
DStidy_2021 %>%
  drop_na(Location) %>%
  ggplot(mapping = aes(x = Location, fill = `English Needed`)) +
  geom_bar(position = "fill") +
  stat_count(geom = "text", mapping = aes(label = stat(count)),
             position = position_fill(vjust = 0.5), colour = "white") +
  labs(x = "Country", y = "Proportion") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), legend.position = "top") +
  coord_flip()

```


## Column {data-width=500, .tabset}

### English Requirement by Job Field
```{r, echo=FALSE, warning=FALSE, message=FALSE}
DStidy_2021 %>%
  drop_na(Job_Field) %>%
  ggplot(mapping = aes(x = Job_Field, fill = `English Needed`)) +
  geom_bar(position = "fill") +
  stat_count(geom = "text", mapping = aes(label = stat(count)),
             position = position_fill(vjust = 0.5), colour = "white") +
  labs(x = "Job Field", y = "Proportion") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), legend.position = "top") +
  coord_flip()

```


### English Requirement by Job Category
```{r, echo=FALSE, warning=FALSE, message=FALSE}
DStidy_2021 %>%
  drop_na(Job_Category) %>%
  ggplot(mapping = aes(x = Job_Category, fill = `English Needed`)) +
  geom_bar(position = "fill") +
  stat_count(geom = "text", mapping = aes(label = stat(count)),
             position = position_fill(vjust = 0.5), colour = "white") +
  labs(x = "Job Category", y = "Proportion") +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), legend.position = "top") 

```
